// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tasks.proto

package taskspb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Expression           string   `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Task) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

type SaveOneTaskRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Task                 *Task    `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveOneTaskRequest) Reset()         { *m = SaveOneTaskRequest{} }
func (m *SaveOneTaskRequest) String() string { return proto.CompactTextString(m) }
func (*SaveOneTaskRequest) ProtoMessage()    {}
func (*SaveOneTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{1}
}

func (m *SaveOneTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveOneTaskRequest.Unmarshal(m, b)
}
func (m *SaveOneTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveOneTaskRequest.Marshal(b, m, deterministic)
}
func (m *SaveOneTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveOneTaskRequest.Merge(m, src)
}
func (m *SaveOneTaskRequest) XXX_Size() int {
	return xxx_messageInfo_SaveOneTaskRequest.Size(m)
}
func (m *SaveOneTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveOneTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveOneTaskRequest proto.InternalMessageInfo

func (m *SaveOneTaskRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SaveOneTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *SaveOneTaskRequest) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type SaveOneTaskReply struct {
	ErrorNumber          int32    `protobuf:"varint,1,opt,name=error_number,json=errorNumber,proto3" json:"error_number,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Task                 *Task    `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveOneTaskReply) Reset()         { *m = SaveOneTaskReply{} }
func (m *SaveOneTaskReply) String() string { return proto.CompactTextString(m) }
func (*SaveOneTaskReply) ProtoMessage()    {}
func (*SaveOneTaskReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{2}
}

func (m *SaveOneTaskReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveOneTaskReply.Unmarshal(m, b)
}
func (m *SaveOneTaskReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveOneTaskReply.Marshal(b, m, deterministic)
}
func (m *SaveOneTaskReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveOneTaskReply.Merge(m, src)
}
func (m *SaveOneTaskReply) XXX_Size() int {
	return xxx_messageInfo_SaveOneTaskReply.Size(m)
}
func (m *SaveOneTaskReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveOneTaskReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveOneTaskReply proto.InternalMessageInfo

func (m *SaveOneTaskReply) GetErrorNumber() int32 {
	if m != nil {
		return m.ErrorNumber
	}
	return 0
}

func (m *SaveOneTaskReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SaveOneTaskReply) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type DeleteOneTaskRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TaskKey              string   `protobuf:"bytes,2,opt,name=taskKey,proto3" json:"taskKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOneTaskRequest) Reset()         { *m = DeleteOneTaskRequest{} }
func (m *DeleteOneTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOneTaskRequest) ProtoMessage()    {}
func (*DeleteOneTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{3}
}

func (m *DeleteOneTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOneTaskRequest.Unmarshal(m, b)
}
func (m *DeleteOneTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOneTaskRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOneTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOneTaskRequest.Merge(m, src)
}
func (m *DeleteOneTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOneTaskRequest.Size(m)
}
func (m *DeleteOneTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOneTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOneTaskRequest proto.InternalMessageInfo

func (m *DeleteOneTaskRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteOneTaskRequest) GetTaskKey() string {
	if m != nil {
		return m.TaskKey
	}
	return ""
}

type DeleteOneTaskReply struct {
	ErrorNumber          int32    `protobuf:"varint,1,opt,name=error_number,json=errorNumber,proto3" json:"error_number,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOneTaskReply) Reset()         { *m = DeleteOneTaskReply{} }
func (m *DeleteOneTaskReply) String() string { return proto.CompactTextString(m) }
func (*DeleteOneTaskReply) ProtoMessage()    {}
func (*DeleteOneTaskReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{4}
}

func (m *DeleteOneTaskReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOneTaskReply.Unmarshal(m, b)
}
func (m *DeleteOneTaskReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOneTaskReply.Marshal(b, m, deterministic)
}
func (m *DeleteOneTaskReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOneTaskReply.Merge(m, src)
}
func (m *DeleteOneTaskReply) XXX_Size() int {
	return xxx_messageInfo_DeleteOneTaskReply.Size(m)
}
func (m *DeleteOneTaskReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOneTaskReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOneTaskReply proto.InternalMessageInfo

func (m *DeleteOneTaskReply) GetErrorNumber() int32 {
	if m != nil {
		return m.ErrorNumber
	}
	return 0
}

func (m *DeleteOneTaskReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type KillOneTaskRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TaskKey              string   `protobuf:"bytes,2,opt,name=taskKey,proto3" json:"taskKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillOneTaskRequest) Reset()         { *m = KillOneTaskRequest{} }
func (m *KillOneTaskRequest) String() string { return proto.CompactTextString(m) }
func (*KillOneTaskRequest) ProtoMessage()    {}
func (*KillOneTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{5}
}

func (m *KillOneTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillOneTaskRequest.Unmarshal(m, b)
}
func (m *KillOneTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillOneTaskRequest.Marshal(b, m, deterministic)
}
func (m *KillOneTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillOneTaskRequest.Merge(m, src)
}
func (m *KillOneTaskRequest) XXX_Size() int {
	return xxx_messageInfo_KillOneTaskRequest.Size(m)
}
func (m *KillOneTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KillOneTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KillOneTaskRequest proto.InternalMessageInfo

func (m *KillOneTaskRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *KillOneTaskRequest) GetTaskKey() string {
	if m != nil {
		return m.TaskKey
	}
	return ""
}

type KillOneTaskReply struct {
	ErrorNumber          int32    `protobuf:"varint,1,opt,name=error_number,json=errorNumber,proto3" json:"error_number,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillOneTaskReply) Reset()         { *m = KillOneTaskReply{} }
func (m *KillOneTaskReply) String() string { return proto.CompactTextString(m) }
func (*KillOneTaskReply) ProtoMessage()    {}
func (*KillOneTaskReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{6}
}

func (m *KillOneTaskReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillOneTaskReply.Unmarshal(m, b)
}
func (m *KillOneTaskReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillOneTaskReply.Marshal(b, m, deterministic)
}
func (m *KillOneTaskReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillOneTaskReply.Merge(m, src)
}
func (m *KillOneTaskReply) XXX_Size() int {
	return xxx_messageInfo_KillOneTaskReply.Size(m)
}
func (m *KillOneTaskReply) XXX_DiscardUnknown() {
	xxx_messageInfo_KillOneTaskReply.DiscardUnknown(m)
}

var xxx_messageInfo_KillOneTaskReply proto.InternalMessageInfo

func (m *KillOneTaskReply) GetErrorNumber() int32 {
	if m != nil {
		return m.ErrorNumber
	}
	return 0
}

func (m *KillOneTaskReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetOneTaskRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TaskKey              string   `protobuf:"bytes,2,opt,name=taskKey,proto3" json:"taskKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneTaskRequest) Reset()         { *m = GetOneTaskRequest{} }
func (m *GetOneTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GetOneTaskRequest) ProtoMessage()    {}
func (*GetOneTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{7}
}

func (m *GetOneTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneTaskRequest.Unmarshal(m, b)
}
func (m *GetOneTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneTaskRequest.Marshal(b, m, deterministic)
}
func (m *GetOneTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneTaskRequest.Merge(m, src)
}
func (m *GetOneTaskRequest) XXX_Size() int {
	return xxx_messageInfo_GetOneTaskRequest.Size(m)
}
func (m *GetOneTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneTaskRequest proto.InternalMessageInfo

func (m *GetOneTaskRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetOneTaskRequest) GetTaskKey() string {
	if m != nil {
		return m.TaskKey
	}
	return ""
}

type GetOneTaskReply struct {
	ErrorNumber          int32    `protobuf:"varint,1,opt,name=error_number,json=errorNumber,proto3" json:"error_number,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Task                 *Task    `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneTaskReply) Reset()         { *m = GetOneTaskReply{} }
func (m *GetOneTaskReply) String() string { return proto.CompactTextString(m) }
func (*GetOneTaskReply) ProtoMessage()    {}
func (*GetOneTaskReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{8}
}

func (m *GetOneTaskReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneTaskReply.Unmarshal(m, b)
}
func (m *GetOneTaskReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneTaskReply.Marshal(b, m, deterministic)
}
func (m *GetOneTaskReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneTaskReply.Merge(m, src)
}
func (m *GetOneTaskReply) XXX_Size() int {
	return xxx_messageInfo_GetOneTaskReply.Size(m)
}
func (m *GetOneTaskReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneTaskReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneTaskReply proto.InternalMessageInfo

func (m *GetOneTaskReply) GetErrorNumber() int32 {
	if m != nil {
		return m.ErrorNumber
	}
	return 0
}

func (m *GetOneTaskReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetOneTaskReply) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type GetAllTasksRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllTasksRequest) Reset()         { *m = GetAllTasksRequest{} }
func (m *GetAllTasksRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllTasksRequest) ProtoMessage()    {}
func (*GetAllTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{9}
}

func (m *GetAllTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllTasksRequest.Unmarshal(m, b)
}
func (m *GetAllTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllTasksRequest.Marshal(b, m, deterministic)
}
func (m *GetAllTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllTasksRequest.Merge(m, src)
}
func (m *GetAllTasksRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllTasksRequest.Size(m)
}
func (m *GetAllTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllTasksRequest proto.InternalMessageInfo

func (m *GetAllTasksRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetAllTasksReply struct {
	ErrorNumber          int32    `protobuf:"varint,1,opt,name=error_number,json=errorNumber,proto3" json:"error_number,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Tasks                []*Task  `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllTasksReply) Reset()         { *m = GetAllTasksReply{} }
func (m *GetAllTasksReply) String() string { return proto.CompactTextString(m) }
func (*GetAllTasksReply) ProtoMessage()    {}
func (*GetAllTasksReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{10}
}

func (m *GetAllTasksReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllTasksReply.Unmarshal(m, b)
}
func (m *GetAllTasksReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllTasksReply.Marshal(b, m, deterministic)
}
func (m *GetAllTasksReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllTasksReply.Merge(m, src)
}
func (m *GetAllTasksReply) XXX_Size() int {
	return xxx_messageInfo_GetAllTasksReply.Size(m)
}
func (m *GetAllTasksReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllTasksReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllTasksReply proto.InternalMessageInfo

func (m *GetAllTasksReply) GetErrorNumber() int32 {
	if m != nil {
		return m.ErrorNumber
	}
	return 0
}

func (m *GetAllTasksReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetAllTasksReply) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "taskspb.Task")
	proto.RegisterType((*SaveOneTaskRequest)(nil), "taskspb.SaveOneTaskRequest")
	proto.RegisterType((*SaveOneTaskReply)(nil), "taskspb.SaveOneTaskReply")
	proto.RegisterType((*DeleteOneTaskRequest)(nil), "taskspb.DeleteOneTaskRequest")
	proto.RegisterType((*DeleteOneTaskReply)(nil), "taskspb.DeleteOneTaskReply")
	proto.RegisterType((*KillOneTaskRequest)(nil), "taskspb.KillOneTaskRequest")
	proto.RegisterType((*KillOneTaskReply)(nil), "taskspb.KillOneTaskReply")
	proto.RegisterType((*GetOneTaskRequest)(nil), "taskspb.GetOneTaskRequest")
	proto.RegisterType((*GetOneTaskReply)(nil), "taskspb.GetOneTaskReply")
	proto.RegisterType((*GetAllTasksRequest)(nil), "taskspb.GetAllTasksRequest")
	proto.RegisterType((*GetAllTasksReply)(nil), "taskspb.GetAllTasksReply")
}

func init() { proto.RegisterFile("tasks.proto", fileDescriptor_b3834c8ef8464a3f) }

var fileDescriptor_b3834c8ef8464a3f = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x8f, 0xd2, 0x40,
	0x14, 0xc7, 0x81, 0x52, 0xd1, 0x57, 0x89, 0xf5, 0x85, 0x43, 0x2d, 0xd1, 0xc0, 0x78, 0x31, 0x1e,
	0x38, 0xe0, 0x5f, 0x60, 0x24, 0x36, 0x86, 0xa8, 0x09, 0x72, 0x37, 0x45, 0x5f, 0x4c, 0x65, 0xda,
	0xe9, 0xce, 0x0c, 0x9b, 0xe5, 0x2f, 0xdf, 0xeb, 0xa6, 0x43, 0xe9, 0x4e, 0x29, 0x6c, 0x36, 0x90,
	0xbd, 0xcd, 0xfb, 0xc1, 0xfb, 0x7e, 0x66, 0xde, 0x97, 0x82, 0xa7, 0x63, 0xb5, 0x56, 0x93, 0x5c,
	0x0a, 0x2d, 0xb0, 0x67, 0x82, 0x7c, 0xc5, 0x96, 0xd0, 0x5d, 0xc6, 0x6a, 0x8d, 0x08, 0xdd, 0x2c,
	0x4e, 0x29, 0x68, 0x8f, 0xda, 0x1f, 0x5e, 0x2c, 0xcc, 0x19, 0x03, 0xe8, 0xfd, 0x11, 0x69, 0x1a,
	0x67, 0x7f, 0x83, 0x8e, 0x49, 0xef, 0x43, 0x7c, 0x07, 0x40, 0x37, 0xb9, 0x24, 0xa5, 0x12, 0x91,
	0x05, 0x8e, 0x29, 0x5a, 0x19, 0x96, 0x00, 0xfe, 0x8a, 0xaf, 0xe9, 0x67, 0x46, 0xc5, 0xf0, 0x05,
	0x5d, 0x6d, 0x48, 0x69, 0x1c, 0x80, 0xab, 0xc5, 0x9a, 0xb2, 0x52, 0x64, 0x17, 0xe0, 0x18, 0xba,
	0x05, 0x8c, 0x91, 0xf0, 0xa6, 0xfd, 0x49, 0x49, 0x36, 0x31, 0xbf, 0x34, 0x25, 0x0c, 0xe1, 0xb9,
	0xc8, 0x49, 0xc6, 0x5a, 0xc8, 0x52, 0xac, 0x8a, 0xd9, 0x7f, 0xf0, 0x6b, 0x52, 0x39, 0xdf, 0xe2,
	0x18, 0x5e, 0x92, 0x94, 0x42, 0xfe, 0xce, 0x36, 0xe9, 0x8a, 0xa4, 0xd1, 0x73, 0x17, 0x9e, 0xc9,
	0xfd, 0x30, 0x29, 0xf4, 0xc1, 0x49, 0xd5, 0xbf, 0xf2, 0x5e, 0xc5, 0xb1, 0xe2, 0x70, 0x4e, 0x72,
	0xb0, 0xaf, 0x30, 0x98, 0x11, 0x27, 0xfd, 0xb8, 0x8b, 0x05, 0x60, 0x5e, 0x79, 0x4e, 0xdb, 0xfd,
	0xf3, 0x95, 0x21, 0xfb, 0x06, 0x78, 0x30, 0xe7, 0x5c, 0x6a, 0x36, 0x03, 0x9c, 0x27, 0x9c, 0x5f,
	0x08, 0x14, 0x81, 0x5f, 0x9b, 0x72, 0x36, 0xce, 0x17, 0x78, 0x1d, 0x91, 0xbe, 0x90, 0x26, 0x81,
	0x57, 0xf6, 0x90, 0xa7, 0xdc, 0xe8, 0x47, 0xc0, 0x88, 0xf4, 0x67, 0xce, 0x8b, 0x9c, 0x7a, 0x10,
	0x98, 0x71, 0xf0, 0x6b, 0xbd, 0x67, 0x73, 0xbd, 0x07, 0xd7, 0xa0, 0x04, 0xce, 0xc8, 0x69, 0x82,
	0xed, 0x6a, 0xd3, 0xdb, 0x0e, 0xb8, 0x46, 0x08, 0x23, 0xf0, 0x2c, 0x87, 0xe3, 0xb0, 0x6a, 0x6f,
	0xfe, 0xc5, 0xc2, 0x37, 0xc7, 0x8b, 0x39, 0xdf, 0xb2, 0x16, 0x7e, 0x87, 0x7e, 0xcd, 0x76, 0xf8,
	0xb6, 0xea, 0x3e, 0x66, 0xeb, 0x70, 0x78, 0xaa, 0xbc, 0x1b, 0x17, 0x81, 0x67, 0x99, 0xc6, 0xe2,
	0x6a, 0x1a, 0xd2, 0xe2, 0x3a, 0xf4, 0x19, 0x6b, 0xe1, 0x0c, 0xe0, 0x7e, 0xdf, 0x18, 0x56, 0xad,
	0x0d, 0x27, 0x85, 0xc1, 0xd1, 0x5a, 0x85, 0x63, 0xad, 0xc7, 0xc2, 0x69, 0x2e, 0xd8, 0xc2, 0x39,
	0xdc, 0x28, 0x6b, 0xad, 0x9e, 0x99, 0x4f, 0xe4, 0xa7, 0xbb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62,
	0xfb, 0xea, 0x9b, 0x31, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TasksClient is the client API for Tasks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TasksClient interface {
	SaveOneTask(ctx context.Context, in *SaveOneTaskRequest, opts ...grpc.CallOption) (*SaveOneTaskReply, error)
	DeleteOneTask(ctx context.Context, in *DeleteOneTaskRequest, opts ...grpc.CallOption) (*DeleteOneTaskReply, error)
	KillOneTask(ctx context.Context, in *KillOneTaskRequest, opts ...grpc.CallOption) (*KillOneTaskReply, error)
	GetOneTask(ctx context.Context, in *GetOneTaskRequest, opts ...grpc.CallOption) (*GetOneTaskReply, error)
	GetAllTasks(ctx context.Context, in *GetAllTasksRequest, opts ...grpc.CallOption) (*GetAllTasksReply, error)
}

type tasksClient struct {
	cc *grpc.ClientConn
}

func NewTasksClient(cc *grpc.ClientConn) TasksClient {
	return &tasksClient{cc}
}

func (c *tasksClient) SaveOneTask(ctx context.Context, in *SaveOneTaskRequest, opts ...grpc.CallOption) (*SaveOneTaskReply, error) {
	out := new(SaveOneTaskReply)
	err := c.cc.Invoke(ctx, "/taskspb.Tasks/SaveOneTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksClient) DeleteOneTask(ctx context.Context, in *DeleteOneTaskRequest, opts ...grpc.CallOption) (*DeleteOneTaskReply, error) {
	out := new(DeleteOneTaskReply)
	err := c.cc.Invoke(ctx, "/taskspb.Tasks/DeleteOneTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksClient) KillOneTask(ctx context.Context, in *KillOneTaskRequest, opts ...grpc.CallOption) (*KillOneTaskReply, error) {
	out := new(KillOneTaskReply)
	err := c.cc.Invoke(ctx, "/taskspb.Tasks/KillOneTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksClient) GetOneTask(ctx context.Context, in *GetOneTaskRequest, opts ...grpc.CallOption) (*GetOneTaskReply, error) {
	out := new(GetOneTaskReply)
	err := c.cc.Invoke(ctx, "/taskspb.Tasks/GetOneTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksClient) GetAllTasks(ctx context.Context, in *GetAllTasksRequest, opts ...grpc.CallOption) (*GetAllTasksReply, error) {
	out := new(GetAllTasksReply)
	err := c.cc.Invoke(ctx, "/taskspb.Tasks/GetAllTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TasksServer is the server API for Tasks service.
type TasksServer interface {
	SaveOneTask(context.Context, *SaveOneTaskRequest) (*SaveOneTaskReply, error)
	DeleteOneTask(context.Context, *DeleteOneTaskRequest) (*DeleteOneTaskReply, error)
	KillOneTask(context.Context, *KillOneTaskRequest) (*KillOneTaskReply, error)
	GetOneTask(context.Context, *GetOneTaskRequest) (*GetOneTaskReply, error)
	GetAllTasks(context.Context, *GetAllTasksRequest) (*GetAllTasksReply, error)
}

// UnimplementedTasksServer can be embedded to have forward compatible implementations.
type UnimplementedTasksServer struct {
}

func (*UnimplementedTasksServer) SaveOneTask(ctx context.Context, req *SaveOneTaskRequest) (*SaveOneTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveOneTask not implemented")
}
func (*UnimplementedTasksServer) DeleteOneTask(ctx context.Context, req *DeleteOneTaskRequest) (*DeleteOneTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOneTask not implemented")
}
func (*UnimplementedTasksServer) KillOneTask(ctx context.Context, req *KillOneTaskRequest) (*KillOneTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillOneTask not implemented")
}
func (*UnimplementedTasksServer) GetOneTask(ctx context.Context, req *GetOneTaskRequest) (*GetOneTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneTask not implemented")
}
func (*UnimplementedTasksServer) GetAllTasks(ctx context.Context, req *GetAllTasksRequest) (*GetAllTasksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTasks not implemented")
}

func RegisterTasksServer(s *grpc.Server, srv TasksServer) {
	s.RegisterService(&_Tasks_serviceDesc, srv)
}

func _Tasks_SaveOneTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveOneTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServer).SaveOneTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskspb.Tasks/SaveOneTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServer).SaveOneTask(ctx, req.(*SaveOneTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasks_DeleteOneTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOneTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServer).DeleteOneTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskspb.Tasks/DeleteOneTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServer).DeleteOneTask(ctx, req.(*DeleteOneTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasks_KillOneTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillOneTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServer).KillOneTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskspb.Tasks/KillOneTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServer).KillOneTask(ctx, req.(*KillOneTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasks_GetOneTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServer).GetOneTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskspb.Tasks/GetOneTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServer).GetOneTask(ctx, req.(*GetOneTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasks_GetAllTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServer).GetAllTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskspb.Tasks/GetAllTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServer).GetAllTasks(ctx, req.(*GetAllTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tasks_serviceDesc = grpc.ServiceDesc{
	ServiceName: "taskspb.Tasks",
	HandlerType: (*TasksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveOneTask",
			Handler:    _Tasks_SaveOneTask_Handler,
		},
		{
			MethodName: "DeleteOneTask",
			Handler:    _Tasks_DeleteOneTask_Handler,
		},
		{
			MethodName: "KillOneTask",
			Handler:    _Tasks_KillOneTask_Handler,
		},
		{
			MethodName: "GetOneTask",
			Handler:    _Tasks_GetOneTask_Handler,
		},
		{
			MethodName: "GetAllTasks",
			Handler:    _Tasks_GetAllTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tasks.proto",
}
